### ISSUE TITLE
move to nushell org?

### ISSUE THREAD

**Issue by fdncred** [nushell/nufmt#14]
I'm wondering what the right time is to move this over to the nushell organization. If @AucaCoyan and others are going to keep working on it, I'd move it over now or whenever.

Thoughts?

**Comment by AucaCoyan** [comment]
I'm fine with it!
I will annoy people with my PRs to another account 😂.

The target is `nushell/nufmt` or a crate inside `nushell/nushell`?
I prefer the first one, if available.
In terms of time, I was thinking about moving it when it has _some_ beta functionality. Today you can't even format a simple nu file. But I can keep working on just another remote. That's fine

**Comment by fdncred** [comment]
ok, let's wait then. ping me when you're ready. it will be nushell/nufmt when we do it i think.

**Comment by AucaCoyan** [comment]
Perfect! I'll add milestones in #11 roadmap

**Comment by amtoine** [comment]
i think having it's own repo, i.e. `nushell/nufmt` is better :+1: 

regarding time, i think we could move this right now.
we have `nushell/nupm` which does not even have a single line in it, only a design PR, so that's not a big deal if there's not much in `nufmt` either :wink:

**Comment by fdncred** [comment]
i agree that it's no big deal when we do it. since @AucaCoyan is the main contributor right now, and doing such an excellent job, i'll let him decide when he's ready to move the repo.

**Comment by AucaCoyan** [comment]
Thanks guys!
I'll be short, l promise 💯

**Comment by AucaCoyan** [comment]
With #16 resolved. I think this is ready to keep working at `nushell/nufmt` repo

**Comment by fdncred** [comment]
Looks like we're here now https://github.com/nushell/nufmt
