### ISSUE TITLE
`format_inner` does not remove all trailing newlines

### ISSUE THREAD

**Issue by amtoine** [nushell/nufmt#34]
> Later we would need to fix the failing test, but nonetheless is a step forward!
I'm allright with a merge right now 😄

_Originally posted by @AucaCoyan in https://github.com/nushell/nufmt/issues/31#issuecomment-1602741114_

the test here is the following
```rust
    #[test]
    fn remove_additional_lines() {
        let input = "let one = 1\n\n\n";
        let expected = "let one = 1\n";
        run_test(input, expected);
    }
```

i think it should become
```rust
    #[test]
    fn remove_additional_lines() {
        let input = "let one = 1\n\n\n";
        let expected = "let one = 1";
        run_test(input, expected);
    }
```
> **Note**
> the is no more newlines at the end of `expected` => this was moved out of the responsibility of `format_inner` in #31.

**Comment by AucaCoyan** [comment]
The PR #35 solves this issue 🎉
